42atomys/stud42

web/ui/src/pages/api/auth/[...nextauth].ts

**Relative Issues:** Resolve #271 
Due to the fact of user is pre-loaded in database when he connect in a campus, an user cannot link her account correctly and be stuck in the login page
**Checklist**
no

fix: user already present on database cant link account to her user

---

internal/webhooks/serve.go

**Relative Issues:** https://discord.com/channels/248936708379246593/954510970586284082/1046399942215872572
When a github sponsors cancel her sponsorship, the webhook processor kick the user outside of the beta. With open beta, nobody needs to be kicked out.
**Checklist**
no

fix: github sponsors has kicked out when cancel a sponsorship

---

.github/workflows/discord-push-release.yaml

Since the repository is public, the release message includes embeds. Add a flag to automatically remove all embeds.
**Checklist**
no

chore: remove discord release message embeds

---

internal/api/account_callbacks.go

**Relative Issues:** Resolve #279 
One column on the model user called `is_a_user` must be set as true when an User takes the action to join the app. But actually, the number of active users seems to lower. This PR fix this issue
**Checklist**
no
A manual migration in the database will be perfromed to set all user with duo account linked as active.

fix: the user is not correctly considered as active

---

web/ui/src/lib/clustersMap/campus/vienna.ts

During QA, I noticed the missing of the cluster c3 data on Vienna campus. This is a miss when I do a self-code review on PR #291
**Checklist**
no

fix: missing c3 cluster data on vienna campus

---

cmd/reindexusers.go

**Relative Issues:** Resolve #296 
The reindex user operation cannot be run in production due to users count
**Checklist**
no

fix: operations reindex users reach max meilisearch connection

---

cmd/locations.go
cmd/reindexusers.go
internal/api/api.resolvers.go
internal/models/schema/user.go
internal/pkg/searchengine/meilisearch.go
internal/pkg/searchengine/meilisearch_user_index.go
pkg/utils/slice.go
pkg/utils/slice_test.go

**Relative Issues:** Resolve #300 
With the new search engine deployed in 0.19, the global system works correctly but the final ordering don’t match with the query.
This is due to the usage of IN() sql statement, how don’t keep the order in the result set.
**Checklist**
no

fix: search engine order is not relevant

---

web/ui/src/components/Badge/LocationBadge.tsx
web/ui/src/lib/clustersMap/campus.ts
web/ui/src/lib/clustersMap/campus/helsinki.ts
web/ui/src/lib/clustersMap/campus/malaga.ts
web/ui/src/lib/clustersMap/campus/paris.ts
web/ui/src/lib/clustersMap/campus/vienna.ts
web/ui/src/lib/clustersMap/types.d.ts

**Relative Issues:** https://discord.com/channels/248936708379246593/1049339339441705010
Due to recent update, the identifier extractor will crash on bocal locations.
**Checklist**
no

fix: locations badge on friends page crash due to invalid location

---

web/ui/src/lib/clustersMap/campus/seoul.ts

**Relative Issues:** 
Fix #305 
Previously the C9 rows were written wrong 
(`C9r5` was set for C9 rows 2~4), and it was fixed
**Checklist**
no

fix: fixed row numbers seoul cluster c9 that were wrong

---

deploy/stacks/apps/s42/meilisearch.tf

**Relative Issues:** Resolve #356 
Meilsiearch create a task for each async action. When we perform an update of an object in meilisearch, MS create a task. In 1 week we create million of tasks and that is never cleaned. This PR implement a cronjob who delete old tasks to keep volume clean and small as possible. 
**Checklist**
no

fix: meilisearch tasks is not cleaned and increase the volume size

---

.gitignore
.vscode/tasks.json
build/install-dependencies.sh
web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap

**Relative Issues:** Resolve #371 
The time has hardcoded and the relative time fromNow is not fixed. To prevent a false positive errors in test suite, set the system time for location badge tests to 25/12/2022 and calcul `2 months ago` from 25/10/2022
**Checklist**
no
I also add two tasks to help tests suite in devcontainer

fix: time in the past on badge tests to prevent false errors

---

web/ui/src/lib/clustersMap/campus/seoul.ts

The data sended by the intranet is not align with the campus data on our lib. The prefix of cluster must be `cx1` and not `cX-1`
**Checklist**
no

fix: mismatch between campus data and intra data

---

.github/workflows/ci.yaml

Start a new full ci on tags is not necessary and create double run on main branch rules
**Checklist**
no

chore: disable ci on tags

---

deploy/stacks/cluster/monitoring.tf

Due to alert(https://dashboards.s42.app/alerting/grafana/FNlsjC74k/view?orgId=1), we need to bump storage for loki.
no

fix: bump loki storage

---

.github/workflows/issues.yaml

Issues on project has marked stale with the pressence of label https://github.com/42Atomys/stud42/labels/stale%2Flock%20%F0%9F%94%92. This is due to an incorrect label name on configuration. Bump the operations-per-run params from 30 to 100. 
**Checklist**

fix: issue has marked stale due to incorrect label name

---

.github/workflows/build.yaml
.github/workflows/ci.yaml
.github/workflows/issues.yaml
.github/workflows/linters.yaml
.github/workflows/previews-cleaner.yaml
.github/workflows/tests.yaml

The call to Github API is rate-limited due to anonymous authentication. Let the deps in the makefile for local dev but pass [`setup-protoc` Action](https://github.com/marketplace/actions/setup-protoc) to authenticate the repo in the ci and avoid rate-limiting
**Checklist**
no

fix: install protoc in ci with setup-protoc to avoid rate-limiting by github

---

pkg/duoapi/time.go
pkg/duoapi/time_test.go

The DuoTime have incorrect behavior and crash when duotime byte is a null value. Fix it and add a test suit on the file
**Checklist**
no

fix: duo time crash when unmarshalled value is null

---

internal/models/schema/user.go

When we do a manual operation on database and this operation delete a locations, the deletion of the location delete the associated user. 
**Checklist**
no

fix: delete a location on cascade delete the associated user

---

web/ui/src/lib/github.tsx
web/ui/src/lib/useSessionStorage.ts

The component `Star` for github star information is re-render 4 times on each page and cause useless re-render. Rework this Component to store the star count in session data. This data is not usefull and can be approximated 
**Checklist**
no

fix: stars cause multiples useless render

---

deploy/stacks/cluster/monitoring.tf

**Relative Issues:** https://discord.com/channels/248936708379246593/1023378285935198208/1091194060896743525
This pull request aims to bump the Loki storage capacity for our monitoring tool due to an increase in app usage. This will ensure that our monitoring tool continues to function smoothly, without running into storage limitations that could lead to a degraded monitoring experience.
**Checklist**
no
As our application usage continues to grow, it is crucial to scale our monitoring tool's storage capacity accordingly. This PR ensures that we stay ahead of the curve and maintain a high level of monitoring service for our application infrastructure.

chore: bump loki storage due to app usage

---

web/ui/src/pages/api/auth/[...nextauth].ts

This pull request addresses the issue of slow response times from the 42 API by temporarily increasing the timeout duration. This fix will help to prevent potential issues with the application's performance and user experience, allowing for more efficient handling of requests and improved stability when dealing with slower API responses. Please note that this is a temporary solution, and we will revert to the previous timeout settings once the intra-team resolves the underlying issue with the 42 API's response time.
**Checklist**
no
https://42born2code.slack.com/archives/C0FEKP3P1/p1680973550018469

fix: increase timeout due to 42 api slow response time

---

web/ui/sentry.edge.config.js

This pull request addresses the issue of Sentry not being initialized for the edge runtime environment. The fix ensures that Sentry is properly set up to capture and report errors and performance metrics from the edge runtime. By initializing Sentry for edge runtime, we can better monitor and troubleshoot issues that may arise in this environment, leading to an improved overall application experience and more effective error tracking.
**Checklist**
no

fix: initialize sentry for edge runtime

---

deploy/modules/service/cronjob.tf
deploy/modules/service/deamonset.tf
deploy/modules/service/deployment.tf
deploy/modules/service/statefulset.tf
deploy/modules/service/variables.tf
deploy/stacks/apps/s42/storages.tf

Describe the pull request
This pull request addresses an issue preventing Dragonfly from starting due to disk permission errors. The fix involves modifying the disk permission settings, allowing Dragonfly to access the necessary resources and launch as expected.
**Checklist**
no

fix: dragonfly cannot start due to disk permissions

---

internal/api/api.resolvers.go

This pull request addresses an issue where the error message and the actual limitation of a user's cover do not match.
**Checklist**
no

fix: error and real limitation of user cover doesn't match

---

web/ui/src/pages/settings/profile.tsx

This pull request addresses an issue where uploads to S3 in the production environment are being blocked due to CORS (Cross-Origin Resource Sharing) issues. The fix involves changing the fetch mode to 'no-cors', thereby allowing these uploads to proceed without triggering CORS restrictions.
**Checklist**
no

fix: production block s3 upload due to cors

---

web/ui/src/components/Search/Search.tsx
web/ui/src/components/Search/types.d.ts

This pull request addresses an issue where the search loader is displayed indefinitely, which can give users the impression that the application is stuck or unresponsive. The fix involves implementing proper termination conditions for the search loader, ensuring that it is displayed only while a search operation is in progress and hidden once the operation is complete. This modification will enhance the user experience by providing more accurate feedback on the search process, thereby preventing potential confusion and frustration.
**Checklist**

fix: search loader is displayed for eternity

---

web/ui/src/components/UserCard/UserCard.tsx

This pull request addresses an issue where long names on user cards are overflowing their containers without truncation, disrupting the visual design and potentially hindering readability. The fix involves implementing CSS rules to correctly truncate long names with an ellipsis, thereby preserving the design integrity of the user card and enhancing readability. 
**Checklist**

fix: long name on user card overflow without truncate

---

config/stud42.example.yaml
deploy/stacks/apps/configs/stud42/stud42.yaml.tftpl
internal/api/api.resolvers.go
web/ui/src/pages/settings/profile.tsx

This pull request addresses an issue where the upload process to S3 in OVH differs from the standard S3 specifications. The fix involves aligning the upload process with the standard S3 protocol, ensuring compatibility and smooth operation. This fix allow user to upload and access in public-read aby cover uploaded
**Checklist**

fix: upload to s3 in ovh differ than s3 specs

---

web/ui/src/components/ClusterMap/ClusterTableMap.tsx
web/ui/src/components/ClusterMap/index.ts
web/ui/src/lib/clustersMap/types.d.ts
web/ui/src/pages/clusters/[campusName]/[cluster].tsx

This pull request introduces a new entity that adds a personal workspace entity on the cluster map. The addition of personal workspaces on the map provides users with a visual representation of their personal workspace within the cluster. This addition aims to improve user interaction and understanding of their workspace distribution in the cluster, allowing users to easily identify where they can work with their personal computers.
**Checklist**

feat: add personal workspace entity on cluster map

---

web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap
web/ui/src/lib/clustersMap/campus/paris.ts
web/ui/src/lib/searchEngine.ts

The link from the friends page on Paris campus is invalid due to regexp and the fact that location can have uppercase letters

fix: paris campus locations regexp

---

web/ui/src/components/UserProfile/UserProfile.tsx

This pull request addresses an issue where a deprecated main cursus was being displayed first. The fix involves revising the cursus display order to prioritize current cursus over deprecated ones. Fix #479 
**Checklist**

fix: deprecated main cursus has displayed first

---

web/ui/src/pages/friends/[groupSlug].tsx

This pull request fix a display glitch on friendship page title when no emoji are present in the group name. As emoji feature are not implemented yet, the display will be optional.
**Checklist**

fix: incorrect title page of friendships

---

web/ui/src/components/Search/Search.tsx
web/ui/src/containers/clusters/ClusterSidebar.tsx

This PR addresses a bug where the loading spinner in the cluster search bar would continue to spin indefinitely when a user performs a search.
**Checklist**

fix: loader on cluster search bar spin forever

---

internal/api/api.resolvers.go
web/ui/src/lib/clustersMap/campus/angouleme.ts
web/ui/src/lib/clustersMap/campuses.generated.ts
web/ui/src/lib/clustersMap/types.generated.d.ts

Added the Angouleme campus to the cluster map.
**Checklist**

feat: add angouleme cluster map

---

web/ui/src/pages/settings/profile.tsx

This pull request reflect the new settings page URL on the oauth2 callback. Actually the callback redirect to a 404 Not Found error page.
Resolve #578 
**Checklist**

fix: oauth2 redirects point to a 404

---

internal/webhooks/campus_user.go
internal/webhooks/location.go
internal/webhooks/serve.go
internal/webhooks/user.go

An issue when webhooks are unmarshalled into an interface and not a struct.
**Checklist**

fix: webhooks processor unamrshal empty interface

---

web/ui/src/lib/clustersMap/campus/tokyo.ts

moved from Roppongi to Shinjuku campus
PR for issue #591 
**Checklist**
tokyo.ts transpiles but I couldn't run tests locally so please tell me any issues.

feat: Update tokyo.ts

---

internal/models/utils.go
internal/webhooks/location.go
pkg/duoapi/locations.go

This pull request resolves an issue that occurs when the 42 intranet sends an event to the webhook processor to create a new location for an anonymized (3b3-) user. By design, this should never happen on the intra side, but when it does, it causes a significant increase in the size of RabbitMQ. Therefore, I have implemented a protection mechanism to prevent this.
**Checklist**

fix: intra send location create event for 3b3 users

---

internal/webhooks/types.go
pkg/otelgql/otelgql.go

We encountered a critical issue where the webhook associated with GitHub Sponsorships is causing a system crash. The crash occurs due to an unexpected error in the payload format received from the webhook
**Checklist**

fix: webhook on github sponsorship cause crash due to an error or format
