cmd/campus.go
campus crawler don't update campus data if the campus is already present in database.
**Checklist**
no
=> fix: campus crawler don't update new values

.devcontainer/devcontainer.json, .vscode/tasks.json, docs/devcontainers/README.md
Some explications are missing
**Checklist**
yes/no
=> chore: update devcontainers readme

.devcontainer/Dockerfile, build/Makefile, build/install-dependencies.sh, go.mod, web/ui/package.json, web/ui/yarn.lock
**Relative Issues:** #298 
This add the support of Apple Mac M1 (arm64) on the Devcontainer on the repository. 
**Checklist**
no
=> feat: add support of mac m1 on devcontainers

README.md
I've found a typo in the main README.md and the sentence where it's located seems a bit off, so I fixed the typo and proposed a better wording!
No
=> Typo + wording fix in README.md

web/ui/src/components/Emoji/Emoji.tsx
**Relative Issues:** Resolve #377 
maxcdn dont exist anymore, change to another cdn resolver
**Checklist**
no
=> fix: change emoji cdn

web/ui/next.config.js, web/ui/src/pages/beta/index.tsx
**Relative Issues:** #364 #387 
I decide to add more visibility to the beta access page over the requirement and the automation.
**Checklist**
no
=> chore: make requirement of the beta like star and follow more visible on beta access page

deploy/stacks/apps/s42/api.tf, deploy/stacks/apps/s42/interface.tf, deploy/stacks/apps/s42/jwtks_service.tf, deploy/stacks/apps/s42/meilisearch.tf, deploy/stacks/apps/s42/storages.tf, deploy/stacks/apps/s42/webhook_processor.tf, deploy/stacks/apps/webhooked/webhooked.tf, deploy/stacks/cluster/monitoring.tf, deploy/stacks/pre-cluster/operators.tf
After two weeks of monitoring of financial issues, adjust container size to reduce price 
**Checklist**
=> chore: adjust resource calculated over two weeks of finops

.github/workflows/packages.yaml
The paths of the GitHub actions are incorrect and do not trigger updates on the main push. Additionally, the RabbitMQ version is not being updated in the correct file.
**Checklist**
no
=> fix: rabbitmq version is not updated correctly

.gitignore, api/graphs/api.graphqls, gqlgen.yml, internal/api/api.resolvers.go, web/ui/jest.config.ts, web/ui/package.json, web/ui/src/components/ClusterMap/ClusterTableMap.tsx, web/ui/src/components/NewFeaturePing/NewFeaturePing.tsx, web/ui/src/components/UserCard/DropDownMenu.tsx, web/ui/src/components/UserCard/UserCard.tsx, web/ui/src/components/UserCard/types.d.ts, web/ui/src/components/UserPopup/UserPopup.tsx, web/ui/src/contexts/currentUser.tsx, web/ui/src/contexts/currentUserContext.tsx, web/ui/src/contexts/types.d.ts, web/ui/src/graphql/definitions.gql, web/ui/src/lib/github.tsx, web/ui/src/lib/storageKeys.ts, web/ui/src/lib/useLocalStorage.ts, web/ui/src/lib/useSettings.ts, web/ui/src/pages/_app.tsx, web/ui/src/pages/friends/[groupSlug].tsx, web/ui/src/pages/settings/apparence.tsx, web/ui/tsconfig.json, web/ui/yarn.lock
This pull request focuses on reworking the current user implementation and removing deprecated API fields from the application. The chore involves refactoring the way the application handles user information, ensuring a more efficient and maintainable approach. Additionally, this PR cleans up the codebase by eliminating deprecated API fields, reducing potential confusion and making it easier to maintain the application moving forward.
**Checklist**
no
I also move file how store the storage keys to unified them into one file
=> chore: rework current user and remove deprecated api fields

deploy/stacks/apps/s42/api.tf, deploy/stacks/apps/s42/storages.tf
This pull request addresses an issue where Dragonfly is experiencing connectivity issues in production environments. The fix involves refining the network configuration and connection settings for Dragonfly, specifically when deployed in production. 
**Checklist**
no
=> fix: dragonfly connectivity on production envs

pull_request_template.md
Update the pull request template to remove breaking changes (due to the fact the conventional commit integrate the breaking change behaviour) and changes the checklist to be more accurate with the actual stage of the project
=> chore: update the pull request template

web/ui/src/components/UserCard/UserCard.tsx
This pull request addresses an issue where the dropdown menu on the user card is being cropped, hindering its usability. The fix involves adjusting the CSS rules and layout properties of the dropdown menu to ensure that it is fully visible and accessible.
**Checklist**
=> fix: drodown menu on user card is cropped

web/ui/src/components/UserCard/UserCard.tsx, web/ui/src/pages/settings/profile.tsx
Reverting no cors mode un user cover upload due to fetch api dont allow this mode with put method. Will create another pr with a fixed cors deployement.
**Checklist**
=> chore: revert no cors mode

web/ui/src/contexts/currentUser.tsx, web/ui/src/pages/settings/apparence.tsx
This pull request addresses an issue where appearance settings are not correctly applied to the DOM. The fix involves refining the process through which these settings are propagated to the DOM, ensuring that user-specified appearance configurations are accurately reflected. By resolving this issue, we enhance the application's responsiveness to user settings and improve the overall user experience.
**Checklist**
=> fix: apparence settings is not correctly applied to the dom

web/ui/package.json, web/ui/src/contexts/currentUser.tsx, web/ui/src/pages/_app.tsx, web/ui/src/pages/api/auth/[...nextauth].ts, web/ui/yarn.lock
This pull request addresses an issue causing latency and white theme flickering due to problems with next-auth. The fix involves resolving these next-auth issues by rollback to client side session fetching and eliminate the undesirable flickering effect by rolling back the client cache on local storage.
**Checklist**
The latency seams to be when nextauth try to store new session on response cookies. Maybe is a next issue. We put some metadata to the transactions for a better monitoring on Sentry
=> fix: latency and white theme flickering caused by next-auth issues 

web/ui/src/lib/clustersMap/campus/tokyo.ts, web/ui/src/lib/clustersMap/index.ts, web/ui/src/lib/clustersMap/types.d.ts
Added the Tokyo campus information following the tutorial on https://github.com/42atomys/stud42/wiki/Contributions
**Checklist**
I didn't manage to open the application in my Browser to see the changes (localhost:3000 keeps loading without displaying anything)
Also, I'm sorry, I don't know how to run the linter...
link to the issue #347
=> Add Tokyo campus

web/ui/package.json, web/ui/src/contexts/currentUser.tsx, web/ui/src/pages/_app.tsx, web/ui/yarn.lock
This pull request addresses an issue where themes blink on the first page load. The fix involves refining the theme loading process to prevent this blinking effect, providing a smoother, more visually consistent user experience.
**Checklist**
=> fix: theme are blinking on first page load

.github/workflows/ci.yaml, .github/workflows/discord-push-release.yaml, .github/workflows/tests.yaml
This pull request involves refactoring some behaviors of our GitHub workflows. The goal of this task is to enhance the efficiency, reliability, and readability of our CI/CD processes by adjusting certain aspects of our workflow configuration. Remove the deploy step on every main push and remove terraform test from fork to prevent error state.
**Checklist**
=> refactor: change some behavior of github workflows

web/ui/src/components/Form/FileInput.tsx, web/ui/src/components/Form/SelectInput.tsx, web/ui/src/components/Search/Search.tsx, web/ui/src/components/Sidebar/Sidebar.tsx, web/ui/src/components/Sidebar/SidebarMenu.tsx, web/ui/src/containers/settings/SettingsCategory.tsx, web/ui/src/lib/github.tsx, web/ui/src/pages/_document.tsx, web/ui/src/pages/friends/[groupSlug].tsx, web/ui/src/pages/settings/accounts.tsx
This pull request addresses an issue of color mismatch across different themes. The fix involves harmonizing the color definitions for each theme, ensuring consistency and adherence to the intended design. 
**Checklist**
=> fix: colors mismatch on themes

deploy/stacks/cluster/configs/monitoring/loki.yaml, deploy/stacks/cluster/configs/monitoring/tempo.yaml, deploy/stacks/cluster/monitoring.tf
This pull request involves a major version upgrade of our monitoring stack. The goal of this task is to keep our application up-to-date with the latest enhancements, bug fixes, and potential performance improvements offered by this new version. By updating to the latest version of our monitoring stack, we aim to ensure the optimal performance, reliability, and feature set of our monitoring capabilities, ensuring we can effectively track and manage the health and performance of our application.
**Checklist**
=> chore: upgrade monitoring stack major version

deploy/stacks/apps/s42/storages.tf
This pull request involves upgrading our database system to PostgreSQL 15 in production environment. By moving to PostgreSQL 15, we take advantage of the latest improvements, enhancements, and security updates of this database management system. 
**Checklist**
=> chore: upgrade to postgresql 15 in production

deploy/modules/service/main.tf, deploy/stacks/apps/.terraform.lock.hcl, deploy/stacks/apps/s42/crawlers.tf, deploy/stacks/apps/s42/locals.tf
This pull request addresses an issue where certain mapped campuses have invalid locations. As a workaround to ensure the accessibility and accuracy of campus data, we've opted to enable all crawlers for all mapped campuses.
**Checklist**
=> fix: enable crawler for all mapped campuses as a workaround

web/ui/src/containers/settings/SettingsLayout.tsx, web/ui/src/lib/prototypes/string.js, web/ui/src/pages/clusters/[campusName]/[cluster].tsx, web/ui/src/pages/feed/index.tsx, web/ui/src/pages/friends/[groupSlug].tsx, web/ui/src/pages/index.tsx, web/ui/src/pages/statistics/index.tsx, web/ui/src/types/globals.d.ts
This PR addresses an oversight where numerous pages within the application lacked appropriate window titles. Ensuring each page has a meaningful title is essential for navigation, and accessibility purposes.
**Checklist**
=> fix: a lot of pages don't have window title

web/ui/src/lib/clustersMap/campus/madrid.ts, web/ui/src/lib/clustersMap/index.ts, web/ui/src/lib/clustersMap/types.d.ts
Added Madrid cluster map
Resolves 42atomys/stud42#336
=> Adding madrid cluster map

web/ui/src/containers/settings/SettingsLayout.tsx, web/ui/src/pages/clusters/[campusSlug]/[clusterSlug].tsx, web/ui/src/pages/friends/[groupSlug].tsx
React render comments on title page due to presence of multiple jsx elements in SSR. 
**Checklist**
=> fix: react render comment on page title

deploy/stacks/apps/s42/meilisearch.tf
This pull request do the upgrade to the latest version of meilisearch (v1.4.2) and use the first stable version of the app
**Checklist**
=> chore: upgrade to meilisearch v1.4.2

internal/webhooks/serve.go
Fix an issue on the webhooks processor, where the payload are unserialized into an interface. 
**Checklist**
=> fix: webhooks processor deserialize into an interface

deploy/stacks/apps/s42/locals.tf
This pull request enable the backup sync strategy for all activated campus (as a workaround of intra instability)
**Checklist**
=> chore: enable backup sync for all campus

deploy/stacks/apps/configs/webhooked/github_template.tpl
A JSON synthax error cause error on webhooks processor.
**Checklist**
=> fix: github webhooked template json synthax error
